package br.com.celcoin.commercialpaperimporter.emission.framework.output.persist.data;

import br.com.celcoin.commercialpaperimporter.infrastructure.config.Constants;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "PLACEHOLDER_PRODUCTS_TABLE_NAME")
public class IssuanceData {

    public static final String ISSUANCE_TABLE_NAME = "cpi-issuance-data1";

    @DynamoDBHashKey(attributeName = Constants.IssuanceData.ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = Constants.IssuanceData.ESCRITURATOR_CNPJ)
    private String cnpjDoEscriturador;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ISSUANCE_NUMBER)
    private String numeroDaEmissao;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ID_INTEGRATION)
    private String idItegration;


    @DynamoDBAttribute(attributeName = Constants.IssuanceData.REQUEST_ID)
    private String requestId;

    @DynamoDBIndexRangeKey(attributeName = Constants.IssuanceData.SERIES_NUMBER, localSecondaryIndexName = Constants.IssuanceData.SERIES_NUMBER_LSI)
    private String numeroDaSerie;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.TYPE)
    private String tipo;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.STATUS)
    private String status;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ISSUANCE_DATE)
    private String dataDaEmissao;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ISSUANCE_EXPIRE_DATE)
    private String dataDoVencimento;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.LOCAL_OF_ISSUE)
    private String localDaEmissao;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.UF_OF_THE_EMISSION)
    private String ufDaEmissao;

    // DADOS FINANCEIROS
    @DynamoDBAttribute(attributeName = Constants.IssuanceData.COST_OF_ISSUE)
    private String custoDaEmissao;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.NOMINAL_UNITAR_VALUE)
    private String valorNominalUnitario;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.AMOUNT)
    private String quantidade;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.PERCENTUAL_FOR_INTEREST_REMUNERATORIES)
    private String percentualDosJurosRemuneratorios;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.INDEXER_PERCENTAGE)
    private String percentualDoIndexador;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.INDEXER)
    private String indexador;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.CONVENTION)
    private String convencao;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.PAYMENT_PLACE)
    private String localDePagamento;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.UF_OF_PAGMENT)
    private String ufDePagamento;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.TYPE_OF_PAYMENT)
    private String tipoDePagamento;

    // TABELA PRICE
    @DynamoDBAttribute(attributeName = Constants.IssuanceData.PERCENTAGE_OF)
    private String percentualSobre;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.DUE_FIRST_INSTALLMENT)
    private String vencimentoDa1aParcela;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.FREQUENCY)
    private String periodicidade;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.PERIOD)
    private String periodo;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ISSUER_CNPJ)
    private String cnpjDoEmissor;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.INVESTORS)
    private String investidoresJson;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.CREATE_DATE)
    private String createDate;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.UPDATE_DATE)
    private String updateDate;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.ID_ATTACH_SIGNED_TERM)
    private String idAttachSignedTerm;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.LINK)
    private String link;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.BUCKET_NAME)
    private String bucketName;

    @DynamoDBAttribute(attributeName = Constants.IssuanceData.KEY_NAME)
    private String keyName;

}
